name: fraser_env

channels:
  - conda-forge
  - bioconda

dependencies:
  # ---------------------------
  # R CORE
  # ---------------------------
  - r-base=4.5
  - r-essentials

  # ---------------------------
  # FRASER CORE STACK (LOCKED COMPATIBLE)
  # ---------------------------
  - bioconductor-fraser
  - bioconductor-delayedarray
  - bioconductor-summarizedexperiment
  - bioconductor-s4vectors
  - bioconductor-biocparallel
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-biobase
  - bioconductor-biostrings
  - bioconductor-rsamtools
  - bioconductor-xvector

  # Annotation
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
  - bioconductor-org.hs.eg.db

  # ---------------------------
  # CRAN SAFE (NO COMPILATION)
  # ---------------------------
  - r-data.table
  - r-curl
  - r-httr

  # system libs (important stability)
  - libcurl
  - openssl
  - zlib
